[template variables]
SITE="ncm"
MAINCYCLE="P30D"
POSTCYCLE="P1M"
cpuOCN=238
cpuATM=1024
nUPPjobs=4
nNodes=20
wpsInputSec=21600
cpuPerNode=64
atmOutFreqMins=180
atmFileFreqMins=720
ocnOutFreqSecs=21600
atmDT=45
ocnDT=60
cplDT=180
ACCOUNT=""
nTimesInWRFout=4
uppNtasks=32
PLATFORM="cluster"

SKRIPS_DIR = "/g/home/pgopinathan/SKRIPS" 
PYTHON="/g/home/pgopinathan/miniforge3/bin/python" 
PARALLEL="/g/home/pgopinathan/miniforge3/bin/parallel" 
ISODATETIME="/g/home/pgopinathan/bin/isodatetime" 
POST_PATH="/g/home/pgopinathan/POST_PATH" 
ARCHIVE_PATH="/g260/ccc/pgopinathan/ARCHIVE" 
ERA_DATA="/g260/ccc/data-from-kaust/ERA5_grib2/ERA5" 
GLORYS_DATA="/g260/ccc/data-from-kaust/SKRIPS_DATA/AP8km4km/GLORYS_bnd" 

GEO_EM_FILE = "/g/home/pgopinathan/SKRIP_Grids/AP/4km/8km/geo_em.d01_mod.nc" 
BATHY_FILE = "/g/home/pgopinathan/SKRIP_Grids/AP/4km/bathymetry.bin" 
MITGRID_FILE = "/g/home/pgopinathan/SKRIP_Grids/AP/4km/tile001.mitgrid" 
