[template variables]
SITE="shaheen3"
cpuOCN=238
cpuATM=1024
nUPPjobs=4

nio_tasks_per_group=6
nio_groups=32

nNodes=7
cpuPerNode=192
ACCOUNT="k10035"
uppNtasks=32
PLATFORM="shaheen3"
DATAMOVER="shaheen3"

SKRIPS_DIR = "/project/k10035/athippp/SKRIPS" 
PYTHON="/lustre2/project/k10035/athippp/miniforge3/bin/python" 
GRIB_COPY="/lustre2/project/k10035/athippp/miniforge3/bin/grib_copy" 
CDO="/lustre2/project/k10035/athippp/miniforge3/bin/cdo" 
ISODATETIME="/project/k10035/athippp/.local/bin/isodatetime" 
POST_PATH="/scratch/athippp/TMP_OUT/" 
ARCHIVE_PATH="/project/k10035/athippp/ARCHIVE" 
ERA_DATA="/scratch/project/k10035/athippp/DATA/ERA5" 
GLORYS_DATA="/scratch/project/k10035/athippp/DATA/GLORYS_bnd" 

GEO_EM_FILE = "/scratch/project/k10035/athippp/SKRIP_Grids/AP/4km/8km/geo_em.d01_mod.nc" 
BATHY_FILE = "/scratch/project/k10035/athippp/SKRIP_Grids/AP/4km/bathymetry.bin" 
MITGRID_FILE = "/scratch/project/k10035/athippp/SKRIP_Grids/AP/4km/tile001.mitgrid" 

